{
    "Service": "/TravelApp/Services/TravelApp.service",
    "DefiningRequests": [{
        "Name": "TravelRequest",
        "Query": "TravelRequest"
    }],
    "_Type": "Action.Type.OfflineOData.Download",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnFailure": "/TravelApp/Actions/com_initium_hpcl/Service/SyncFailureMessage.action",
    "OnSuccess": "/TravelApp/Rules/ErrorArchive/ErrorArchive_CheckForSyncError.js"
}