{
    "Service": "/TravelApp/Services/TravelApp.service",
    "DefiningRequests": [{
        "Name": "TravelRequest",
        "Query": "TravelRequest"
    }],
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText": "Downloading...",
    "ActionResult": {
        "_Name": "init"
    },
    "OnFailure": "/TravelApp/Actions/com_initium_hpcl/Service/InitializeOfflineFailureMessage.action"
}