{
    "Message": "Upload in progress...",
    "CompletionMessage": "Sync completed",
    "CompletionTimeout": 7,
    "OnSuccess": "/TravelApp/Actions/com_initium_hpcl/Service/UploadOffline.action",
    "OnFailure": "/TravelApp/Actions/com_initium_hpcl/Service/SyncFailureMessage.action",
    "_Type": "Action.Type.ProgressBanner"
}