{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "approveRequestSrv"
	},
	"OnFailure": "/TravelApp/Actions/ApproveErrorMsg.action",
	"OnSuccess": "/TravelApp/Actions/ApproveSuccessMsg.action",
	"Target": {
		"Service": "/TravelApp/Services/TravelApp.service",
		"EntitySet": "TravelRequest",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"ID": "{ID}",
		"Status": "Approved"
	}
}