{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "ApproveSuccessMsg"
	},
	"Message": "Travel request Approved successfully",
	"OKCaption": "OK",
	"OnOK": "/TravelApp/Actions/CloseModalPage_Complete.action"
}