{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "createFlightDetailsSrv"
	},
	"OnSuccess": "/TravelApp/Actions/CloseModalPage_Complete.action",
	"Target": {
		"Service": "/TravelApp/Services/TravelApp.service",
		"EntitySet": "BoardingPass"
	},
	"Properties": {
		"flightNo": "#Control:FCFlightNo/#Value",
		"flightFrom": "#Control:FCFlightFrom/#Value",
		"flightTo": "#Control:FCFlightTo/#Value",
		"seatNo": "#Control:FCSeatNo/#Value",
		"boardingDate": "#Control:FCBoardingDate/#Value",
		"attachmentId": "/TravelApp/Rules/createFlightDetails.js",
		"req_ID": "{ID}"
	}
}