{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "RequestRejectedSuccessMsg"
	},
	"OnSuccess": "/TravelApp/Actions/CloseModalPage_Complete.action",
	"Message": "Request rejected successfully",
	"OKCaption": "OK"
}