{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "updateTravelDetailsErrorMsg"
	},
	"Message": "Failed to update travel details - {#ActionResults:updateTravelRequestSrv/error}",
	"OKCaption": "OK"
}